### ISSUE TITLE
Hybrid and hybrid forward

### ISSUE THREAD

**Issue by samhodge** [zhanghang1989/MXNet-Gluon-Style-Transfer#2]
I was trying to put a symbol into the model and save it as a symbolic network, but many of the Hybrid things only implement forward and not hybrid_forward.

I am struggling to do this myself.

do you know if anybody else has already done this as an exercise.

I am stuck on Inspiration(HybridBlock)

I was able to do Reflectance padding on my own after reading this document:

http://gluon.mxnet.io/chapter07_distributed-learning/hybridize.html

Any help would be apprieciated.

It would be a textbook example of being able to train in Python and deploy in C++

Sam

**Comment by zhanghang1989** [comment]
Sorry that I am not familiar with symbol API. You may ask in the mxnet repo.

**Comment by samhodge** [comment]
Thanks for responding I will continue trying and ask on the mxnet repo

**Comment by samhodge** [comment]
Reported to mxnet repo
