### ISSUE TITLE
fail to open "models\mxvgg.params"

### ISSUE THREAD

**Issue by exitNA** [zhanghang1989/MXNet-Gluon-Style-Transfer#3]
hi:
    I have tried to run
 ```
python main.py optim --content-image images/content/venice-boat.jpg --style-image images/styles/candy.jpg
```
but I got an error:
```
LocalFileSystem: fail to open "models\mxvgg.params"
```

I have checked the models dir, which there is no mxvgg.params file, but it has an download_model.sh script, 
then, but it only download **21styles.params** no **mxvgg.params**. 
where can i find **mxvgg.params**?

**Comment by zhanghang1989** [comment]
It should be automatically downloaded https://github.com/zhanghang1989/MXNet-Gluon-Style-Transfer/blob/master/utils.py#L207

**Comment by exitNA** [comment]
ok，thanks
