### ISSUE TITLE
Question about upsampled convolution

### ISSUE THREAD

**Issue by Edmospheric-pressure** [zhanghang1989/MXNet-Gluon-Style-Transfer#4]
Hi Hang,
In the paper, you have proposed an upsampled convolution to replace traditional deconvolution. However, in the code, it seems that upsampling + convolution is used instead of your proposed upsampled conv. May I ask how to implement your version of upsampled convolution?

Best,
Ed

**Comment by zhanghang1989** [comment]
This code is out-of-date. Please see the implementation here http://hangzh.com/PyTorch-Encoding/nn.html?highlight=upsampleconv2d#encoding.nn.UpsampleConv2d
